name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: production

    steps:
      - uses: actions/checkout@v3

      - name: Move build to /var/www/reservafazendamodelo
        run: |
          rm -rf /var/www/reservafazendamodelo/*
          mv build/* /var/www/reservafazendamodelo/
